# Site settings
title: Owen Searls
name: Owen Searls
copyright: Searls Omnimedia 2016
description: "Computer science student at Tufts University"
url: "owen.searls.net"

# Delete the lines you don't need
# about 5 elements are recomended
github_username:  owensearls
facebook_username: owenfsearls 
linked_in_username: your_linked_in_username_goes_here
email: owen@searls.net

front_img: yes
front_img_path: "images/background2.jpg"
#front_img_path: "https://external.url/image.jpg"

# Build settings
markdown: kramdown
permalink: pretty
